import type { ParentScriptEntry } from "./types";

/**
 * RASCUNHO — 50 entradas (10 situações × 5 faixas etárias) escritas seguindo o
 * checklist de PLAN-ferramentas.md (seção 5.3): sem linguagem de diagnóstico
 * clínico, sem tom culpabilizador em relação aos pais, linguagem adequada à
 * faixa etária, frases prontas para serem ditas literalmente, `evitar` sempre
 * com motivo. Precisa de revisão humana (especialista em parentalidade
 * positiva) antes de considerar este conteúdo definitivo/publicado.
 */
export const PARENT_SCRIPTS: ParentScriptEntry[] = [
  // ─── nao_quer_dormir ────────────────────────────────────────────────────────
  {
    key: "nao_quer_dormir__2_4",
    situacao: "nao_quer_dormir",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você não está com sono agora, mas seu corpinho precisa descansar.",
    limite: "Agora é hora de dormir.",
    escolha: "Você quer ouvir uma música calma ou ficar só com a luz de dormir?",
    se_persistir: "Eu vou ficar aqui um minutinho com você até você ficar mais calmo(a).",
    evitar: {
      frase: "Se você não dormir agora, o Papai Noel/a fada não vai vir.",
      motivo: "Ameaças fantasiosas não ensinam a criança a lidar com a dificuldade real de relaxar, só criam medo.",
    },
  },
  {
    key: "nao_quer_dormir__5_7",
    situacao: "nao_quer_dormir",
    faixa_etaria: "5_7",
    validacao: "Eu entendo que você queria continuar brincando um pouco mais.",
    limite: "Mas agora o corpo precisa descansar para amanhã.",
    escolha: "Você quer escolher qual pijama vestir ou qual livrinho olhar antes de dormir?",
    se_persistir: "Vou ficar do seu lado até você se acalmar, mas as luzes já vão ficar apagadas.",
    evitar: {
      frase: "Dorme logo que eu já estou cansada de repetir.",
      motivo: "Focar no seu próprio cansaço em vez do que a criança está sentindo faz ela associar a hora de dormir a um momento de tensão, não de acolhimento.",
    },
  },
  {
    key: "nao_quer_dormir__8_10",
    situacao: "nao_quer_dormir",
    faixa_etaria: "8_10",
    validacao: "Eu sei que às vezes dá vontade de ficar acordado mais um pouco.",
    limite: "Mas o horário de dormir continua sendo esse.",
    escolha: "Você prefere ler mais 10 minutos ou conversar um pouco antes de apagar a luz?",
    se_persistir: "Vamos combinar um sinal — quando eu apagar a luz do corredor, é hora de fechar os olhos.",
    evitar: {
      frase: "Você é grande demais para ainda dar trabalho pra dormir.",
      motivo: "Comparar a criança com uma expectativa de idade gera vergonha em vez de ajudar a resolver a dificuldade real.",
    },
  },
  {
    key: "nao_quer_dormir__11_13",
    situacao: "nao_quer_dormir",
    faixa_etaria: "11_13",
    validacao: "Eu entendo que você quer terminar o que estava fazendo.",
    limite: "Mesmo assim, esse é o horário combinado para dormir.",
    escolha: "Você prefere terminar em 10 minutos com alarme ou já ir agora e continuar amanhã?",
    se_persistir: "Vamos rever esse horário juntos outro dia com calma, mas hoje ele continua valendo.",
    evitar: {
      frase: "Se você não desligar agora eu vou tirar o celular de vez.",
      motivo: "Ameaças desproporcionais tendem a não ser cumpridas à risca e ensinam a criança a testar o limite em vez de respeitá-lo.",
    },
  },
  {
    key: "nao_quer_dormir__14_17",
    situacao: "nao_quer_dormir",
    faixa_etaria: "14_17",
    validacao: "Eu sei que você tem seu próprio ritmo e coisas que quer terminar à noite.",
    limite: "Ainda assim, dormir numa hora razoável importa para o seu bem-estar.",
    escolha: "Você prefere ajustar esse horário 30 minutos ou manter como está e organizar melhor o resto do dia?",
    se_persistir: "Vamos conversar amanhã com calma sobre como ajustar sua rotina de sono.",
    evitar: {
      frase: "Já devia saber se cuidar sozinho a essa altura.",
      motivo: "Cobranças sobre maturidade nesse momento soam como julgamento e fecham a conversa em vez de abrir espaço para ajustar a rotina junto com o adolescente.",
    },
  },

  // ─── fazendo_birra ──────────────────────────────────────────────────────────
  {
    key: "fazendo_birra__2_4",
    situacao: "fazendo_birra",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você está muito bravo(a) agora.",
    limite: "Mas não posso deixar você se machucar ou quebrar as coisas enquanto está assim.",
    escolha: "Quer um abraço ou prefere ficar um pouquinho sozinho(a) até se acalmar?",
    se_persistir: "Eu vou ficar pertinho esperando você se acalmar, sem pressa.",
    evitar: {
      frase: "Para de chorar agora ou vou embora e deixo você aqui.",
      motivo: "Ameaçar abandono, mesmo de brincadeira, mexe com o medo mais profundo da criança pequena e não ensina a regular a emoção.",
    },
  },
  {
    key: "fazendo_birra__5_7",
    situacao: "fazendo_birra",
    faixa_etaria: "5_7",
    validacao: "Eu percebo que você está muito frustrado(a) com isso.",
    limite: "Mesmo assim, gritar ou bater não vai mudar a resposta.",
    escolha: "Você quer respirar fundo comigo ou prefere se acalmar sozinho(a) primeiro?",
    se_persistir: "Tudo bem, vou esperar você ficar pronto(a) para conversar.",
    evitar: {
      frase: "Já falei que não! Para de fazer birra.",
      motivo: "Repetir o 'não' em tom mais alto tende a escalar a birra em vez de ajudar a criança a se regular.",
    },
  },
  {
    key: "fazendo_birra__8_10",
    situacao: "fazendo_birra",
    faixa_etaria: "8_10",
    validacao: "Eu entendo que você ficou bravo(a) com essa situação.",
    limite: "Mas gritar comigo não vai resolver o problema.",
    escolha: "Você quer me contar o que aconteceu agora ou prefere um tempo primeiro?",
    se_persistir: "Estou aqui quando você quiser conversar com mais calma.",
    evitar: {
      frase: "Você está fazendo drama por nada.",
      motivo: "Minimizar o sentimento da criança ensina que a frustração dela não é válida, o que dificulta que ela aprenda a nomear e regular emoções.",
    },
  },
  {
    key: "fazendo_birra__11_13",
    situacao: "fazendo_birra",
    faixa_etaria: "11_13",
    validacao: "Percebo que isso te deixou muito irritado(a).",
    limite: "Ainda assim, não vou continuar essa conversa nesse tom.",
    escolha: "Você quer se acalmar um pouco e voltarmos a falar depois, ou prefere resolver agora com calma?",
    se_persistir: "Vou dar um tempo e retomamos quando os dois estivermos mais tranquilos.",
    evitar: {
      frase: "Você está insuportável, não aguento mais esse jeito.",
      motivo: "Rotular o comportamento como traço da personalidade magoa e faz o pré-adolescente se fechar em vez de dialogar.",
    },
  },
  {
    key: "fazendo_birra__14_17",
    situacao: "fazendo_birra",
    faixa_etaria: "14_17",
    validacao: "Eu vejo que essa situação te tirou do sério.",
    limite: "Mesmo assim, preciso que a conversa continue em outro tom.",
    escolha: "Prefere continuar agora com calma ou pausar e voltar depois?",
    se_persistir: "Tudo bem, retomamos quando fizer sentido para você.",
    evitar: {
      frase: "Na sua idade já devia saber se controlar.",
      motivo: "Cobrar controle emocional como se fosse óbvio ignora que a autorregulação ainda está em desenvolvimento nessa fase e gera mais afastamento.",
    },
  },

  // ─── bateu_no_irmao ─────────────────────────────────────────────────────────
  {
    key: "bateu_no_irmao__2_4",
    situacao: "bateu_no_irmao",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você ficou bravo(a) com seu irmão/irmã.",
    limite: "Mas não posso deixar você bater. Bater machuca.",
    escolha: "Você quer bater na almofada para descarregar ou pedir ajuda para mim?",
    se_persistir: "Vou ficar entre vocês até todo mundo se acalmar.",
    evitar: {
      frase: "Você é malvado(a) por bater no seu irmão.",
      motivo: "Rotular a criança como 'má' ensina uma identidade negativa em vez de corrigir o comportamento específico.",
    },
  },
  {
    key: "bateu_no_irmao__5_7",
    situacao: "bateu_no_irmao",
    faixa_etaria: "5_7",
    validacao: "Entendo que aconteceu alguma coisa que te deixou bravo(a).",
    limite: "Mesmo assim, bater não é permitido aqui.",
    escolha: "Você quer me contar o que houve ou prefere se acalmar primeiro?",
    se_persistir: "Vamos separar vocês um pouco até as coisas esfriarem.",
    evitar: {
      frase: "Bate nele/nela de volta assim ele/ela aprende.",
      motivo: "Incentivar retaliação ensina que a violência resolve conflitos, contrariando exatamente o limite que se está tentando ensinar.",
    },
  },
  {
    key: "bateu_no_irmao__8_10",
    situacao: "bateu_no_irmao",
    faixa_etaria: "8_10",
    validacao: "Percebo que rolou um conflito sério entre vocês.",
    limite: "Bater continua não sendo aceitável, mesmo brigando.",
    escolha: "Você quer me contar sua versão primeiro ou prefere que eu ouça os dois juntos?",
    se_persistir: "Vamos conversar separados até vocês se acalmarem.",
    evitar: {
      frase: "Vocês dois nunca se dão bem, não aguento mais brigas.",
      motivo: "Generalizar a briga como um problema permanente da relação entre os irmãos desanima ambos em vez de resolver o conflito pontual.",
    },
  },
  {
    key: "bateu_no_irmao__11_13",
    situacao: "bateu_no_irmao",
    faixa_etaria: "11_13",
    validacao: "Entendo que a discussão esquentou.",
    limite: "Mesmo assim, agressão física não é como resolvemos as coisas aqui.",
    escolha: "Vocês querem tentar resolver conversando agora ou preferem um tempo separados primeiro?",
    se_persistir: "Vou separar vocês até conseguirmos conversar com calma.",
    evitar: {
      frase: "Vocês são grandes demais pra brigar feito criancinha.",
      motivo: "Comparar com uma expectativa de maturidade gera vergonha em vez de ensinar uma forma melhor de lidar com o conflito.",
    },
  },
  {
    key: "bateu_no_irmao__14_17",
    situacao: "bateu_no_irmao",
    faixa_etaria: "14_17",
    validacao: "Percebo que a situação ficou tensa entre vocês.",
    limite: "Ainda assim, agressão física é limite absoluto aqui em casa.",
    escolha: "Querem conversar sobre o que aconteceu agora, com minha mediação, ou preferem esfriar primeiro?",
    se_persistir: "Vou dar um tempo para os dois e retomamos a conversa depois.",
    evitar: {
      frase: "Se acontecer de novo, nem sei o que vou fazer com vocês dois.",
      motivo: "Ameaças vagas e sem consequência definida geram ansiedade sem ensinar nada prático sobre o limite.",
    },
  },

  // ─── nao_quer_ir_escola ─────────────────────────────────────────────────────
  {
    key: "nao_quer_ir_escola__2_4",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria ficar em casa comigo hoje.",
    limite: "Mas hoje é dia de ir para a escolinha.",
    escolha: "Você quer levar o ursinho na mochila ou prefere ir de mãozinha dada até a porta?",
    se_persistir: "Eu vou te levar com calma, e a tia/o tio vai estar te esperando.",
    evitar: {
      frase: "Se você não for, vou ficar triste e decepcionada com você.",
      motivo: "Colocar a emoção do adulto como peso sobre a decisão da criança gera culpa em vez de ajudar a lidar com a separação.",
    },
  },
  {
    key: "nao_quer_ir_escola__5_7",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "5_7",
    validacao: "Entendo que hoje bateu uma vontade de ficar em casa.",
    limite: "Mesmo assim, hoje é dia de escola.",
    escolha: "Você quer escolher a roupa ou o lanche de hoje?",
    se_persistir: "Vamos com calma, e você pode me contar no caminho o que está sentindo.",
    evitar: {
      frase: "Todo mundo vai pra escola, só você que não quer ir.",
      motivo: "Comparar com outras crianças não resolve o motivo real da resistência e pode aumentar a sensação de estar errado(a) por sentir aquilo.",
    },
  },
  {
    key: "nao_quer_ir_escola__8_10",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "8_10",
    validacao: "Percebo que você não está com vontade de ir hoje.",
    limite: "Ainda assim, hoje é dia de aula.",
    escolha: "Você quer me contar o motivo no caminho ou prefere conversar melhor à noite?",
    se_persistir: "Vamos indo, e depois a gente conversa com calma sobre o que está pegando.",
    evitar: {
      frase: "Você só não quer ir porque é preguiçoso(a).",
      motivo: "Rotular a resistência como preguiça ignora possíveis motivos reais (medo, dificuldade social, cansaço) e fecha a conversa.",
    },
  },
  {
    key: "nao_quer_ir_escola__11_13",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "11_13",
    validacao: "Entendo que hoje você não está com vontade nenhuma de ir.",
    limite: "Mesmo assim, ir para a escola continua sendo necessário.",
    escolha: "Você quer me contar agora o que está pegando ou prefere conversar com calma à noite?",
    se_persistir: "Vamos indo, e a conversa sobre o motivo a gente continua depois.",
    evitar: {
      frase: "Na sua idade não dá mais pra ficar com esse tipo de manha.",
      motivo: "Chamar a resistência de manha despreza um possível motivo real por trás (bullying, ansiedade, dificuldade com uma matéria) que merece ser ouvido.",
    },
  },
  {
    key: "nao_quer_ir_escola__14_17",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "14_17",
    validacao: "Percebo que hoje você está bem resistente à ideia de ir.",
    limite: "Mesmo assim, precisamos manter a frequência na escola.",
    escolha: "Prefere ir e conversarmos sobre o motivo depois, ou conversar rapidamente agora antes de sair?",
    se_persistir: "Vamos indo, e reservamos um tempo hoje à noite para conversar com calma sobre isso.",
    evitar: {
      frase: "Se você não for, vai ficar sem seus privilégios até aprender a ter responsabilidade.",
      motivo: "Punir sem entender o motivo por trás da resistência pode ignorar sinais importantes (ansiedade, conflito social) que precisam de escuta, não só de consequência.",
    },
  },

  // ─── nao_quer_guardar_brinquedos ────────────────────────────────────────────
  {
    key: "nao_quer_guardar_brinquedos__2_4",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria continuar brincando.",
    limite: "Mas agora é hora de guardar.",
    escolha: "Você quer guardar os bichinhos ou os blocos primeiro?",
    se_persistir: "Eu vou te ajudar a guardar, vamos fazer juntos.",
    evitar: {
      frase: "Se você não guardar, vou jogar tudo no lixo.",
      motivo: "Ameaças exageradas sobre os pertences da criança geram medo desproporcional e não ensinam o hábito de organizar.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__5_7",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "5_7",
    validacao: "Eu sei que você queria continuar brincando.",
    limite: "Mas agora é hora de guardar os brinquedos.",
    escolha: "Você quer guardar primeiro os carrinhos ou os blocos?",
    se_persistir: "Eu vou te ajudar a começar. Você guarda esses e eu guardo aqueles.",
    evitar: {
      frase: "Se você não guardar agora, nunca mais vai brincar.",
      motivo: "Ameaças desproporcionais não são cumpridas na prática e enfraquecem a confiança da criança no limite.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__8_10",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "8_10",
    validacao: "Entendo que dá preguiça de parar a brincadeira para guardar.",
    limite: "Mesmo assim, guardar faz parte de terminar a brincadeira.",
    escolha: "Você prefere guardar agora ou combinar um horário certinho para isso hoje?",
    se_persistir: "Vou ficar por perto enquanto você guarda, sem fazer por você.",
    evitar: {
      frase: "Você é tão desorganizado(a), nunca aprende.",
      motivo: "Rotular a criança como 'desorganizada' vira uma etiqueta que ela carrega, em vez de tratar como um hábito ainda em construção.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__11_13",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "11_13",
    validacao: "Entendo que organizar as próprias coisas às vezes parece perda de tempo.",
    limite: "Mesmo assim, manter o quarto em ordem continua sendo sua responsabilidade.",
    escolha: "Você prefere organizar agora ou definir um horário fixo esta semana para isso?",
    se_persistir: "Vamos combinar um prazo curto para isso ficar resolvido hoje.",
    evitar: {
      frase: "Seu quarto parece uma bagunça só, que vergonha.",
      motivo: "Comentários humilhantes sobre o espaço da criança atacam a autoestima em vez de ajudar a construir o hábito de organização.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__14_17",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "14_17",
    validacao: "Entendo que organizar suas coisas não é prioridade agora.",
    limite: "Ainda assim, isso continua sendo parte do combinado de casa.",
    escolha: "Você prefere resolver isso hoje ou definir um dia fixo na semana para manter em ordem?",
    se_persistir: "Vamos revisar juntos esse combinado se ele não estiver funcionando.",
    evitar: {
      frase: "Você é um bagunceiro, não muda nunca.",
      motivo: "Rótulos definitivos fecham a possibilidade de mudança em vez de abrir espaço para ajustar o combinado.",
    },
  },

  // ─── mentiu ─────────────────────────────────────────────────────────────────
  {
    key: "mentiu__2_4",
    situacao: "mentiu",
    faixa_etaria: "2_4",
    validacao: "Eu percebo que você tinha medo de me contar a verdade.",
    limite: "Mas é importante me contar o que realmente aconteceu.",
    escolha: "Você quer me contar agora ou precisa de um minutinho para pensar?",
    se_persistir: "Tudo bem, vou esperar. Quando quiser me contar, estarei aqui.",
    evitar: {
      frase: "Você é um mentiroso(a), não confio mais em você.",
      motivo: "Rotular a criança pequena como 'mentirosa' cria uma identidade negativa antes mesmo de ela entender bem a diferença entre fantasia e mentira.",
    },
  },
  {
    key: "mentiu__5_7",
    situacao: "mentiu",
    faixa_etaria: "5_7",
    validacao: "Eu entendo que você ficou com medo de se meter em problema.",
    limite: "Mesmo assim, prefiro sempre saber a verdade, mesmo que seja difícil.",
    escolha: "Você quer me contar agora do seu jeito ou prefere que eu pergunte por partes?",
    se_persistir: "Vou esperar você se sentir pronto(a) para contar.",
    evitar: {
      frase: "Nunca mais vou acreditar em nada que você disser.",
      motivo: "Declarar desconfiança permanente por um episódio isolado é desproporcional e pode fazer a criança desistir de tentar ser sincera no futuro.",
    },
  },
  {
    key: "mentiu__8_10",
    situacao: "mentiu",
    faixa_etaria: "8_10",
    validacao: "Percebo que você tentou evitar um problema contando outra versão.",
    limite: "Mesmo assim, mentir piora a situação em vez de resolver.",
    escolha: "Você quer me contar a verdade agora ou prefere escrever o que aconteceu?",
    se_persistir: "Vou esperar, mas precisamos conversar sobre isso ainda hoje.",
    evitar: {
      frase: "Você é igualzinho a quem sempre mente nessa família.",
      motivo: "Comparar a criança a outra pessoa da família reforça um rótulo herdado em vez de tratar o episódio como algo pontual e corrigível.",
    },
  },
  {
    key: "mentiu__11_13",
    situacao: "mentiu",
    faixa_etaria: "11_13",
    validacao: "Entendo que talvez tenha parecido mais fácil não contar a verdade.",
    limite: "Mesmo assim, prefiro lidar com a verdade, mesmo quando é complicada.",
    escolha: "Você quer me contar agora o que realmente aconteceu ou prefere um tempo para organizar as ideias?",
    se_persistir: "Vou esperar, mas essa conversa precisa acontecer.",
    evitar: {
      frase: "Não sei mais quando você está falando a verdade.",
      motivo: "Embora pareça uma constatação simples, dita de forma acusatória isso mina a confiança do adolescente na possibilidade de reconstruir a relação.",
    },
  },
  {
    key: "mentiu__14_17",
    situacao: "mentiu",
    faixa_etaria: "14_17",
    validacao: "Entendo que pode ter parecido mais simples não contar tudo.",
    limite: "Ainda assim, prefiro sempre a versão real dos fatos, mesmo que gere consequência.",
    escolha: "Você quer me contar agora com calma ou prefere um tempo antes de conversarmos?",
    se_persistir: "Tudo bem, mas vamos precisar retomar essa conversa em breve.",
    evitar: {
      frase: "Você decepcionou toda a família com essa mentira.",
      motivo: "Colocar o peso da família inteira sobre um erro individual é desproporcional e gera vergonha excessiva em vez de responsabilização construtiva.",
    },
  },

  // ─── esta_com_medo ──────────────────────────────────────────────────────────
  {
    key: "esta_com_medo__2_4",
    situacao: "esta_com_medo",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você está com muito medo agora.",
    limite: "Estou aqui com você, você não está sozinho(a).",
    escolha: "Você quer um abraço ou prefere segurar minha mão?",
    se_persistir: "Vou ficar bem pertinho até você se sentir mais seguro(a).",
    evitar: {
      frase: "Não tem nada disso, para de ser bobo(a).",
      motivo: "Negar o medo da criança pequena não faz o medo desaparecer, só ensina que os sentimentos dela não devem ser mostrados.",
    },
  },
  {
    key: "esta_com_medo__5_7",
    situacao: "esta_com_medo",
    faixa_etaria: "5_7",
    validacao: "Eu entendo que isso te deixou com medo.",
    limite: "Estou aqui e vamos passar por isso juntos.",
    escolha: "Você quer conversar sobre o que te assustou ou prefere só ficar pertinho de mim agora?",
    se_persistir: "Tudo bem, vamos com calma, no seu tempo.",
    evitar: {
      frase: "Isso é coisa de bebê ter medo disso.",
      motivo: "Comparar o medo a um comportamento 'de bebê' envergonha a criança em vez de ajudá-la a lidar com o que sente.",
    },
  },
  {
    key: "esta_com_medo__8_10",
    situacao: "esta_com_medo",
    faixa_etaria: "8_10",
    validacao: "Percebo que isso realmente te assustou.",
    limite: "Vamos conversar sobre isso com calma.",
    escolha: "Você quer me contar o que aconteceu ou prefere um tempo antes de falar sobre isso?",
    se_persistir: "Estou aqui, sem pressa nenhuma.",
    evitar: {
      frase: "Você já é grande, não devia ter medo disso.",
      motivo: "Medir o medo pela idade ignora que cada criança processa situações de forma diferente e reforça a ideia de que sentir medo é motivo de vergonha.",
    },
  },
  {
    key: "esta_com_medo__11_13",
    situacao: "esta_com_medo",
    faixa_etaria: "11_13",
    validacao: "Entendo que essa situação te deixou apreensivo(a).",
    limite: "Vamos conversar sobre isso e pensar juntos no que pode ajudar.",
    escolha: "Você quer falar sobre isso agora ou prefere organizar os pensamentos primeiro?",
    se_persistir: "Tudo bem, estou aqui quando quiser conversar.",
    evitar: {
      frase: "Isso não é motivo pra tanto medo, você está exagerando.",
      motivo: "Minimizar o medo do pré-adolescente como exagero pode fazer com que ele pare de compartilhar o que sente no futuro.",
    },
  },
  {
    key: "esta_com_medo__14_17",
    situacao: "esta_com_medo",
    faixa_etaria: "14_17",
    validacao: "Entendo que essa situação gerou insegurança em você.",
    limite: "Estou aqui para conversar sobre isso sempre que precisar.",
    escolha: "Você quer conversar agora sobre o que está sentindo ou prefere pensar um pouco antes?",
    se_persistir: "Sem pressa, continuo disponível quando você quiser falar.",
    evitar: {
      frase: "Você já é quase adulto, tem que superar isso sozinho.",
      motivo: "Cobrar autossuficiência emocional precoce isola o adolescente justamente no momento em que mais precisa de apoio.",
    },
  },

  // ─── esta_chorando ──────────────────────────────────────────────────────────
  {
    key: "esta_chorando__2_4",
    situacao: "esta_chorando",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você está bem triste ou chateado(a).",
    limite: "Está tudo bem chorar, eu estou aqui.",
    escolha: "Você quer colo ou prefere só ficar pertinho de mim?",
    se_persistir: "Vou ficar aqui até você se acalmar, sem pressa nenhuma.",
    evitar: {
      frase: "Para de chorar já, não é nada demais.",
      motivo: "Dizer que o motivo 'não é nada' invalida o sentimento da criança, que ainda não tem repertório para relativizar sozinha.",
    },
  },
  {
    key: "esta_chorando__5_7",
    situacao: "esta_chorando",
    faixa_etaria: "5_7",
    validacao: "Percebo que você está bem triste com isso.",
    limite: "Pode chorar, eu vou ficar aqui com você.",
    escolha: "Você quer me contar o que houve agora ou prefere só chorar um pouco primeiro?",
    se_persistir: "Sem pressa, estou bem aqui do seu lado.",
    evitar: {
      frase: "Já chega de choro, você está fazendo drama.",
      motivo: "Rotular o choro como 'drama' ensina a criança a esconder a tristeza em vez de expressá-la de forma saudável.",
    },
  },
  {
    key: "esta_chorando__8_10",
    situacao: "esta_chorando",
    faixa_etaria: "8_10",
    validacao: "Entendo que isso te machucou de verdade.",
    limite: "Pode chorar à vontade, eu vou ficar por perto.",
    escolha: "Você quer conversar sobre o que houve ou prefere um tempo sozinho(a) primeiro?",
    se_persistir: "Tudo bem, venho te ver daqui a pouquinho.",
    evitar: {
      frase: "Já é grande, não chora por isso.",
      motivo: "Associar choro a idade ensina a reprimir a emoção em vez de expressá-la, o que tende a voltar de outras formas mais difíceis depois.",
    },
  },
  {
    key: "esta_chorando__11_13",
    situacao: "esta_chorando",
    faixa_etaria: "11_13",
    validacao: "Percebo que isso te afetou bastante.",
    limite: "Pode ficar à vontade para sentir isso, estou aqui.",
    escolha: "Você quer conversar agora ou prefere um tempo sozinho(a) primeiro?",
    se_persistir: "Sem problema, fico por perto para quando quiser conversar.",
    evitar: {
      frase: "Para de ser tão sensível, isso não é motivo pra chorar.",
      motivo: "Rotular a sensibilidade como exagero ensina o pré-adolescente a desconfiar da própria percepção emocional.",
    },
  },
  {
    key: "esta_chorando__14_17",
    situacao: "esta_chorando",
    faixa_etaria: "14_17",
    validacao: "Entendo que isso pesou bastante em você.",
    limite: "Pode sentir isso à vontade, não precisa esconder de mim.",
    escolha: "Você quer conversar sobre o que está sentindo ou prefere um tempo sozinho(a) antes?",
    se_persistir: "Tudo bem, continuo disponível quando você quiser.",
    evitar: {
      frase: "Não sei por que você está chorando por uma bobagem dessas.",
      motivo: "Classificar o motivo como bobagem desqualifica a experiência do adolescente e fecha a porta para ele compartilhar sentimentos no futuro.",
    },
  },

  // ─── nao_aceita_desligar_celular ────────────────────────────────────────────
  {
    key: "nao_aceita_desligar_celular__2_4",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria continuar vendo ou brincando na tela.",
    limite: "Mas agora é hora de desligar.",
    escolha: "Você quer desligar sozinho(a) ou prefere que eu conte até três com você?",
    se_persistir: "Vou desligar com calma, e podemos fazer outra coisa juntos agora.",
    evitar: {
      frase: "Se não desligar agora, nunca mais vejo tela nenhuma.",
      motivo: "Ameaças absolutas e improváveis de cumprir ensinam a criança a não levar o limite a sério.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__5_7",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "5_7",
    validacao: "Entendo que você queria terminar o que estava vendo ou jogando.",
    limite: "Mas o tempo de tela combinado já terminou.",
    escolha: "Você quer desligar agora ou terminar essa fase/vídeo em 2 minutos?",
    se_persistir: "Vou te ajudar a desligar, e a gente já vai para a próxima atividade.",
    evitar: {
      frase: "Você fica igual um zumbi na tela, isso é um vício.",
      motivo: "Usar linguagem de 'vício' numa criança pequena é desproporcional e não ajuda a construir um hábito saudável de uso de tela.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__8_10",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "8_10",
    validacao: "Entendo que é difícil parar no meio de um jogo ou vídeo.",
    limite: "Mesmo assim, o tempo combinado acabou.",
    escolha: "Você prefere pausar agora e retomar depois, ou terminar essa etapa em 5 minutos?",
    se_persistir: "Vou ficar aqui até você desligar, sem pressa.",
    evitar: {
      frase: "Só sabe ficar grudado nessa tela, não presta pra mais nada.",
      motivo: "Generalizar o comportamento como um traço negativo da criança gera vergonha em vez de ajudar a construir um limite claro de uso de tela.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__11_13",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "11_13",
    validacao: "Entendo que no meio de uma partida ou vídeo é mais difícil parar.",
    limite: "Mesmo assim, o horário combinado para desligar é esse.",
    escolha: "Você prefere desligar agora ou terminar a rodada atual em poucos minutos?",
    se_persistir: "Vamos revisar esse combinado juntos se ele não estiver funcionando bem.",
    evitar: {
      frase: "Vou tirar seu celular de vez se você não desligar.",
      motivo: "Ameaças desproporcionais tendem a não ser cumpridas à risca, o que ensina a criança a testar o limite em vez de respeitá-lo.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__14_17",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "14_17",
    validacao: "Entendo que interromper algo no meio incomoda.",
    limite: "Ainda assim, o horário combinado para desligar continua valendo.",
    escolha: "Prefere desligar agora ou terminar em alguns minutos com um alarme marcado?",
    se_persistir: "Vamos rever esse combinado com calma outro dia se ele não estiver fazendo sentido.",
    evitar: {
      frase: "Vocês dessa geração são todos viciados em celular.",
      motivo: "Generalizações sobre a geração soam como julgamento amplo e afastam o adolescente da conversa sobre o limite específico daquele momento.",
    },
  },

  // ─── falou_desrespeitoso ────────────────────────────────────────────────────
  {
    key: "falou_desrespeitoso__2_4",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você está bravo(a).",
    limite: "Mas não posso deixar você falar assim comigo.",
    escolha: "Você quer tentar falar de outro jeito ou prefere um tempo para se acalmar primeiro?",
    se_persistir: "Vou esperar você se acalmar para continuarmos a conversa.",
    evitar: {
      frase: "Não fala assim comigo, sua peste!",
      motivo: "Responder com um rótulo negativo modela exatamente o comportamento que se está tentando corrigir.",
    },
  },
  {
    key: "falou_desrespeitoso__5_7",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "5_7",
    validacao: "Entendo que você está bravo(a) com a situação.",
    limite: "Mesmo assim, não vou aceitar ser tratada assim.",
    escolha: "Você quer tentar de novo com outras palavras ou prefere um tempinho antes?",
    se_persistir: "Vou esperar você se acalmar para conversarmos com respeito.",
    evitar: {
      frase: "Cadê a educação que eu te dei?",
      motivo: "Essa frase transforma um comportamento pontual em um julgamento sobre a criação da criança, o que gera culpa sem ensinar a alternativa.",
    },
  },
  {
    key: "falou_desrespeitoso__8_10",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "8_10",
    validacao: "Percebo que você está bravo(a) com alguma coisa.",
    limite: "Mesmo assim, esse tom não é aceitável aqui.",
    escolha: "Você quer tentar me dizer de outro jeito o que está sentindo?",
    se_persistir: "Vou esperar você se acalmar antes de continuarmos.",
    evitar: {
      frase: "Você está mal-educado(a) que nem [alguém da família].",
      motivo: "Comparações desse tipo reforçam rótulos herdados em vez de tratar o comportamento como algo pontual e corrigível.",
    },
  },
  {
    key: "falou_desrespeitoso__11_13",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "11_13",
    validacao: "Entendo que algo te deixou irritado(a).",
    limite: "Mesmo assim, não vou continuar a conversa nesse tom.",
    escolha: "Você quer tentar de novo com outro tom ou prefere pausar e retomar depois?",
    se_persistir: "Vou dar um tempo e retomamos quando estiver mais calmo(a).",
    evitar: {
      frase: "Você está muito mal-educado(a), não sei o que fazer com você.",
      motivo: "Expressar desamparo do adulto transfere a responsabilidade da situação para a criança, que não tem ferramentas para resolver isso sozinha.",
    },
  },
  {
    key: "falou_desrespeitoso__14_17",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "14_17",
    validacao: "Entendo que você está incomodado(a) com algo.",
    limite: "Ainda assim, preciso que a conversa continue com respeito.",
    escolha: "Prefere retomar com outro tom agora ou pausar e conversarmos mais tarde?",
    se_persistir: "Vou pausar essa conversa e retomamos quando os dois estivermos mais calmos.",
    evitar: {
      frase: "Enquanto morar sob meu teto, vai me respeitar.",
      motivo: "Frases que usam autoridade baseada em dependência financeira/moradia soam como ameaça de poder, o que tende a gerar mais afastamento do que respeito genuíno.",
    },
  },
];
