import type { ParentScriptEntry } from "./types";

/**
 * RASCUNHO — 90 entradas (18 situações × 5 faixas etárias) escritas seguindo o
 * checklist de PLAN-ferramentas.md (seção 5.3): sem linguagem de diagnóstico
 * clínico, sem tom culpabilizador em relação aos pais, linguagem adequada à
 * faixa etária, frases prontas para serem ditas literalmente (tom coloquial,
 * do jeito que um pai/mãe realmente fala no dia a dia — evitando vocabulário
 * de livro/acadêmico), `evitar` sempre com motivo em linguagem simples.
 * Precisa de revisão humana (especialista em parentalidade positiva) antes de
 * considerar este conteúdo definitivo/publicado.
 */
export const PARENT_SCRIPTS: ParentScriptEntry[] = [
  // ─── nao_quer_dormir ────────────────────────────────────────────────────────
  {
    key: "nao_quer_dormir__2_4",
    situacao: "nao_quer_dormir",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você não tá com sono ainda, mas o corpinho precisa descansar.",
    limite: "Agora é hora de dormir.",
    escolha: "Quer ouvir uma música calminha ou só ficar com a luz de dormir acesa?",
    se_persistir: "Vou ficar aqui um minutinho com você até você se acalmar.",
    evitar: {
      frase: "Se você não dormir agora, o Papai Noel não vem.",
      motivo: "Ameaça inventada só assusta, não ensina a criança a relaxar de verdade.",
    },
  },
  {
    key: "nao_quer_dormir__5_7",
    situacao: "nao_quer_dormir",
    faixa_etaria: "5_7",
    validacao: "Eu sei que você queria brincar mais um pouco.",
    limite: "Mas agora o corpo precisa descansar pra amanhã.",
    escolha: "Quer escolher o pijama ou o livrinho de hoje?",
    se_persistir: "Fico do seu lado até você se acalmar, mas já vou apagar a luz.",
    evitar: {
      frase: "Dorme logo que eu já tô cansada de repetir.",
      motivo: "Focar no seu próprio cansaço em vez do que a criança sente faz a hora de dormir virar briga, não descanso.",
    },
  },
  {
    key: "nao_quer_dormir__8_10",
    situacao: "nao_quer_dormir",
    faixa_etaria: "8_10",
    validacao: "Eu sei que dá vontade de ficar acordado mais um pouco.",
    limite: "Mas o horário de dormir continua sendo esse.",
    escolha: "Quer ler mais 10 minutos ou conversar um pouco antes de apagar a luz?",
    se_persistir: "Vamos combinar um sinal: quando eu apagar a luz do corredor, é hora de fechar o olho.",
    evitar: {
      frase: "Você já tá grande pra ainda dar trabalho pra dormir.",
      motivo: "Comparar com uma idade 'certa' só envergonha, não resolve a dificuldade de verdade.",
    },
  },
  {
    key: "nao_quer_dormir__11_13",
    situacao: "nao_quer_dormir",
    faixa_etaria: "11_13",
    validacao: "Eu entendo que você quer terminar o que tava fazendo.",
    limite: "Mesmo assim, esse é o horário combinado pra dormir.",
    escolha: "Prefere terminar em 10 minutos com alarme ou já ir agora e continuar amanhã?",
    se_persistir: "A gente revê esse horário com calma outro dia, mas hoje ele continua valendo.",
    evitar: {
      frase: "Se você não desligar agora eu tiro o celular de vez.",
      motivo: "Ameaça grande demais pra cumprir ensina a testar o limite, não a respeitar.",
    },
  },
  {
    key: "nao_quer_dormir__14_17",
    situacao: "nao_quer_dormir",
    faixa_etaria: "14_17",
    validacao: "Eu sei que você tem seu próprio ritmo à noite.",
    limite: "Ainda assim, dormir numa hora razoável importa pro seu bem-estar.",
    escolha: "Prefere ajustar esse horário em 30 minutos ou manter e organizar melhor o resto do dia?",
    se_persistir: "Vamos conversar amanhã com calma sobre ajustar sua rotina de sono.",
    evitar: {
      frase: "Já devia saber se cuidar sozinho a essa altura.",
      motivo: "Cobrança assim soa como julgamento e fecha a conversa, em vez de ajudar a ajustar a rotina junto.",
    },
  },

  // ─── fazendo_birra ──────────────────────────────────────────────────────────
  {
    key: "fazendo_birra__2_4",
    situacao: "fazendo_birra",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você tá com muita raiva agora.",
    limite: "Mas não posso deixar você se machucar ou quebrar as coisas.",
    escolha: "Quer um abraço ou prefere ficar um pouquinho sozinho até se acalmar?",
    se_persistir: "Vou ficar pertinho esperando você se acalmar, sem pressa.",
    evitar: {
      frase: "Para de chorar agora ou eu vou embora e deixo você aqui.",
      motivo: "Ameaçar abandono, mesmo de brincadeira, mexe com o medo mais forte da criança pequena.",
    },
  },
  {
    key: "fazendo_birra__5_7",
    situacao: "fazendo_birra",
    faixa_etaria: "5_7",
    validacao: "Eu vejo que isso te deixou super frustrado.",
    limite: "Mesmo assim, gritar ou bater não vai mudar a resposta.",
    escolha: "Quer respirar fundo comigo ou prefere se acalmar sozinho primeiro?",
    se_persistir: "Tudo bem, eu espero você ficar pronto pra conversar.",
    evitar: {
      frase: "Já falei que não! Para com essa birra.",
      motivo: "Repetir o 'não' mais alto costuma piorar a birra em vez de ajudar a criança a se acalmar.",
    },
  },
  {
    key: "fazendo_birra__8_10",
    situacao: "fazendo_birra",
    faixa_etaria: "8_10",
    validacao: "Eu entendo que você ficou bravo com isso.",
    limite: "Mas gritar comigo não vai resolver o problema.",
    escolha: "Quer me contar o que aconteceu agora ou prefere um tempo primeiro?",
    se_persistir: "Tô aqui quando você quiser conversar com mais calma.",
    evitar: {
      frase: "Você tá fazendo drama por nada.",
      motivo: "Dizer que não é nada faz a criança achar que o que ela sente não vale, e isso dificulta ela aprender a lidar com a raiva.",
    },
  },
  {
    key: "fazendo_birra__11_13",
    situacao: "fazendo_birra",
    faixa_etaria: "11_13",
    validacao: "Percebo que isso te irritou bastante.",
    limite: "Ainda assim, não vou continuar essa conversa nesse tom.",
    escolha: "Quer se acalmar um pouco e a gente conversa depois, ou prefere resolver agora com calma?",
    se_persistir: "Vou dar um tempo e a gente retoma quando os dois estiverem mais tranquilos.",
    evitar: {
      frase: "Você tá insuportável, não aguento mais esse jeito.",
      motivo: "Chamar o comportamento de 'jeito' da pessoa magoa e afasta, em vez de abrir espaço pra conversar.",
    },
  },
  {
    key: "fazendo_birra__14_17",
    situacao: "fazendo_birra",
    faixa_etaria: "14_17",
    validacao: "Eu vejo que isso te tirou do sério.",
    limite: "Mesmo assim, preciso que a conversa continue em outro tom.",
    escolha: "Prefere continuar agora com calma ou dar um tempo e voltar depois?",
    se_persistir: "Tudo bem, a gente retoma quando fizer sentido pra você.",
    evitar: {
      frase: "Na sua idade já devia saber se controlar.",
      motivo: "Cobrar controle emocional como se fosse óbvio ignora que isso ainda tá em construção nessa fase, e só afasta mais.",
    },
  },

  // ─── bateu_no_irmao ─────────────────────────────────────────────────────────
  {
    key: "bateu_no_irmao__2_4",
    situacao: "bateu_no_irmao",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você ficou bravo com seu irmão.",
    limite: "Mas não posso deixar você bater. Bater machuca.",
    escolha: "Quer bater na almofada pra descarregar ou pedir ajuda pra mim?",
    se_persistir: "Vou ficar entre vocês até todo mundo se acalmar.",
    evitar: {
      frase: "Você é mau por bater no seu irmão.",
      motivo: "Chamar a criança de 'má' cria um rótulo que ela carrega, em vez de corrigir só aquele comportamento.",
    },
  },
  {
    key: "bateu_no_irmao__5_7",
    situacao: "bateu_no_irmao",
    faixa_etaria: "5_7",
    validacao: "Entendo que rolou alguma coisa que te deixou bravo.",
    limite: "Mesmo assim, bater não é permitido aqui.",
    escolha: "Quer me contar o que houve ou prefere se acalmar primeiro?",
    se_persistir: "Vou separar vocês um pouco até as coisas esfriarem.",
    evitar: {
      frase: "Bate nele de volta assim ele aprende.",
      motivo: "Incentivar a bater de volta ensina que violência resolve as coisas — o contrário do que a gente quer ensinar.",
    },
  },
  {
    key: "bateu_no_irmao__8_10",
    situacao: "bateu_no_irmao",
    faixa_etaria: "8_10",
    validacao: "Percebo que rolou um climão sério entre vocês.",
    limite: "Bater continua não sendo aceitável, mesmo brigando.",
    escolha: "Quer me contar sua versão primeiro ou prefere que eu ouça os dois juntos?",
    se_persistir: "Vamos conversar separados até vocês se acalmarem.",
    evitar: {
      frase: "Vocês dois nunca se dão bem, não aguento mais briga.",
      motivo: "Tratar como se a briga fosse sempre assim desanima os dois, em vez de resolver só o que aconteceu agora.",
    },
  },
  {
    key: "bateu_no_irmao__11_13",
    situacao: "bateu_no_irmao",
    faixa_etaria: "11_13",
    validacao: "Entendo que a discussão esquentou.",
    limite: "Mesmo assim, agressão física não é como a gente resolve as coisas aqui.",
    escolha: "Vocês querem tentar resolver conversando agora ou preferem um tempo separados primeiro?",
    se_persistir: "Vou separar vocês até conseguirmos conversar com calma.",
    evitar: {
      frase: "Vocês são grandes demais pra brigar que nem criancinha.",
      motivo: "Comparar com uma expectativa de idade só envergonha, em vez de ensinar um jeito melhor de lidar com o conflito.",
    },
  },
  {
    key: "bateu_no_irmao__14_17",
    situacao: "bateu_no_irmao",
    faixa_etaria: "14_17",
    validacao: "Percebo que a situação ficou tensa entre vocês.",
    limite: "Ainda assim, agressão física é um limite que não se discute aqui em casa.",
    escolha: "Querem conversar sobre o que aconteceu agora, com minha ajuda, ou preferem esfriar primeiro?",
    se_persistir: "Vou dar um tempo pros dois e a gente retoma a conversa depois.",
    evitar: {
      frase: "Se acontecer de novo, nem sei o que vou fazer com vocês dois.",
      motivo: "Ameaça vaga sem consequência clara só gera ansiedade, sem ensinar nada de prático sobre o limite.",
    },
  },

  // ─── nao_quer_ir_escola ─────────────────────────────────────────────────────
  {
    key: "nao_quer_ir_escola__2_4",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria ficar em casa comigo hoje.",
    limite: "Mas hoje é dia de ir pra escolinha.",
    escolha: "Quer levar o ursinho na mochila ou prefere ir de mãozinha dada até a porta?",
    se_persistir: "Vou te levar com calma, e a tia vai tá te esperando.",
    evitar: {
      frase: "Se você não for, eu vou ficar triste com você.",
      motivo: "Colocar o sentimento do adulto como peso na decisão da criança gera culpa, em vez de ajudar com a separação.",
    },
  },
  {
    key: "nao_quer_ir_escola__5_7",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "5_7",
    validacao: "Entendo que hoje bateu uma vontade de ficar em casa.",
    limite: "Mesmo assim, hoje é dia de escola.",
    escolha: "Quer escolher a roupa ou o lanche de hoje?",
    se_persistir: "Vamos com calma, e você pode me contar no caminho o que tá sentindo.",
    evitar: {
      frase: "Todo mundo vai pra escola, só você que não quer ir.",
      motivo: "Comparar com outras crianças não resolve o motivo real da resistência, só faz a criança se sentir errada por sentir aquilo.",
    },
  },
  {
    key: "nao_quer_ir_escola__8_10",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "8_10",
    validacao: "Percebo que você não tá com vontade de ir hoje.",
    limite: "Ainda assim, hoje é dia de aula.",
    escolha: "Quer me contar o motivo no caminho ou prefere conversar melhor à noite?",
    se_persistir: "Vamos indo, e depois a gente conversa com calma sobre o que tá pegando.",
    evitar: {
      frase: "Você só não quer ir porque é preguiçoso.",
      motivo: "Chamar de preguiça ignora que pode ter um motivo real por trás — medo, dificuldade com colega, cansaço — e fecha a conversa.",
    },
  },
  {
    key: "nao_quer_ir_escola__11_13",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "11_13",
    validacao: "Entendo que hoje você tá sem vontade nenhuma de ir.",
    limite: "Mesmo assim, ir pra escola continua sendo necessário.",
    escolha: "Quer me contar agora o que tá pegando ou prefere conversar com calma à noite?",
    se_persistir: "Vamos indo, e a conversa sobre o motivo a gente continua depois.",
    evitar: {
      frase: "Na sua idade não dá mais pra ficar com esse tipo de manha.",
      motivo: "Chamar de manha desconsidera um motivo real por trás (bullying, ansiedade, dificuldade numa matéria) que merece ser ouvido.",
    },
  },
  {
    key: "nao_quer_ir_escola__14_17",
    situacao: "nao_quer_ir_escola",
    faixa_etaria: "14_17",
    validacao: "Percebo que hoje você tá bem resistente à ideia de ir.",
    limite: "Mesmo assim, a gente precisa manter a frequência na escola.",
    escolha: "Prefere ir e a gente conversa sobre o motivo depois, ou conversar rapidinho agora antes de sair?",
    se_persistir: "Vamos indo, e reservamos um tempo hoje à noite pra conversar com calma.",
    evitar: {
      frase: "Se você não for, fica sem nada até aprender a ter responsabilidade.",
      motivo: "Punir sem entender o motivo pode ignorar sinais importantes (ansiedade, conflito social) que precisam de escuta, não só de castigo.",
    },
  },

  // ─── nao_quer_guardar_brinquedos ────────────────────────────────────────────
  {
    key: "nao_quer_guardar_brinquedos__2_4",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria continuar brincando.",
    limite: "Mas agora é hora de guardar.",
    escolha: "Quer guardar os bichinhos ou os blocos primeiro?",
    se_persistir: "Vou te ajudar a guardar, vamos fazer juntos.",
    evitar: {
      frase: "Se você não guardar, eu vou jogar tudo fora.",
      motivo: "Ameaça exagerada sobre as coisas da criança dá medo à toa e não ensina o hábito de organizar.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__5_7",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "5_7",
    validacao: "Eu sei que você queria continuar brincando.",
    limite: "Mas agora é hora de guardar os brinquedos.",
    escolha: "Quer guardar primeiro os carrinhos ou os blocos?",
    se_persistir: "Vou te ajudar a começar. Você guarda esses e eu guardo aqueles.",
    evitar: {
      frase: "Se você não guardar agora, nunca mais vai brincar.",
      motivo: "Ameaça grande demais pra cumprir na prática só enfraquece a confiança da criança no limite.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__8_10",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "8_10",
    validacao: "Entendo que dá preguiça de parar a brincadeira pra guardar.",
    limite: "Mesmo assim, guardar faz parte de terminar a brincadeira.",
    escolha: "Prefere guardar agora ou combinar um horário certinho pra isso hoje?",
    se_persistir: "Vou ficar por perto enquanto você guarda, sem fazer por você.",
    evitar: {
      frase: "Você é tão bagunceiro, nunca aprende.",
      motivo: "Chamar de bagunceiro vira um rótulo que a criança carrega, em vez de tratar como um hábito ainda em construção.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__11_13",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "11_13",
    validacao: "Entendo que organizar as próprias coisas às vezes parece perda de tempo.",
    limite: "Mesmo assim, manter o quarto em ordem continua sendo sua parte.",
    escolha: "Prefere organizar agora ou combinar um horário fixo essa semana?",
    se_persistir: "Vamos combinar um prazo curto pra isso ficar resolvido hoje.",
    evitar: {
      frase: "Seu quarto tá um lixo, que vergonha.",
      motivo: "Comentário humilhante sobre o espaço da criança machuca a autoestima, em vez de ajudar a construir o hábito.",
    },
  },
  {
    key: "nao_quer_guardar_brinquedos__14_17",
    situacao: "nao_quer_guardar_brinquedos",
    faixa_etaria: "14_17",
    validacao: "Entendo que organizar suas coisas não é prioridade agora.",
    limite: "Ainda assim, isso continua sendo parte do combinado de casa.",
    escolha: "Prefere resolver isso hoje ou combinar um dia fixo na semana pra manter em ordem?",
    se_persistir: "Vamos rever juntos esse combinado se ele não tiver funcionando.",
    evitar: {
      frase: "Você é um bagunceiro, nunca muda.",
      motivo: "Rótulo definitivo fecha a porta pra mudança, em vez de abrir espaço pra ajustar o combinado.",
    },
  },

  // ─── mentiu ─────────────────────────────────────────────────────────────────
  {
    key: "mentiu__2_4",
    situacao: "mentiu",
    faixa_etaria: "2_4",
    validacao: "Eu percebo que você teve medo de me contar a verdade.",
    limite: "Mas é importante me contar o que aconteceu de verdade.",
    escolha: "Quer me contar agora ou precisa de um minutinho pra pensar?",
    se_persistir: "Tudo bem, eu espero. Quando quiser me contar, tô aqui.",
    evitar: {
      frase: "Você é mentiroso, não confio mais em você.",
      motivo: "Rotular a criança pequena de mentirosa cria uma imagem negativa antes dela nem entender direito a diferença entre fantasia e mentira.",
    },
  },
  {
    key: "mentiu__5_7",
    situacao: "mentiu",
    faixa_etaria: "5_7",
    validacao: "Eu entendo que você ficou com medo de arrumar confusão.",
    limite: "Mesmo assim, prefiro sempre saber a verdade, mesmo que seja difícil.",
    escolha: "Quer me contar agora do seu jeito ou prefere que eu pergunte aos poucos?",
    se_persistir: "Vou esperar você se sentir pronto pra contar.",
    evitar: {
      frase: "Nunca mais vou acreditar em nada que você disser.",
      motivo: "Falar em desconfiar pra sempre por um episódio isolado é exagero, e pode fazer a criança desistir de tentar ser sincera depois.",
    },
  },
  {
    key: "mentiu__8_10",
    situacao: "mentiu",
    faixa_etaria: "8_10",
    validacao: "Percebo que você tentou fugir de um problema contando outra versão.",
    limite: "Mesmo assim, mentir só piora a situação em vez de resolver.",
    escolha: "Quer me contar a verdade agora ou prefere escrever o que aconteceu?",
    se_persistir: "Vou esperar, mas a gente precisa conversar sobre isso ainda hoje.",
    evitar: {
      frase: "Você é igualzinho a fulano que sempre mente.",
      motivo: "Comparar com outra pessoa da família cola um rótulo herdado, em vez de tratar isso como algo pontual e que dá pra resolver.",
    },
  },
  {
    key: "mentiu__11_13",
    situacao: "mentiu",
    faixa_etaria: "11_13",
    validacao: "Entendo que talvez tenha parecido mais fácil não contar a verdade.",
    limite: "Mesmo assim, prefiro lidar com a verdade, mesmo quando é complicada.",
    escolha: "Quer me contar agora o que aconteceu de verdade ou prefere um tempo pra organizar as ideias?",
    se_persistir: "Vou esperar, mas essa conversa precisa acontecer.",
    evitar: {
      frase: "Não sei mais quando você tá falando a verdade.",
      motivo: "Dita desse jeito, essa frase mina a confiança do adolescente em conseguir reconstruir a relação.",
    },
  },
  {
    key: "mentiu__14_17",
    situacao: "mentiu",
    faixa_etaria: "14_17",
    validacao: "Entendo que pode ter parecido mais simples não contar tudo.",
    limite: "Ainda assim, prefiro sempre a versão real dos fatos, mesmo que tenha consequência.",
    escolha: "Quer me contar agora com calma ou prefere um tempo antes da gente conversar?",
    se_persistir: "Tudo bem, mas a gente vai precisar retomar essa conversa em breve.",
    evitar: {
      frase: "Você decepcionou a família toda com essa mentira.",
      motivo: "Colocar o peso da família inteira num erro individual é exagero e gera vergonha demais, em vez de ajudar a se responsabilizar.",
    },
  },

  // ─── esta_com_medo ──────────────────────────────────────────────────────────
  {
    key: "esta_com_medo__2_4",
    situacao: "esta_com_medo",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você tá com muito medo agora.",
    limite: "Tô aqui com você, você não tá sozinho.",
    escolha: "Quer um abraço ou prefere segurar minha mão?",
    se_persistir: "Vou ficar bem pertinho até você se sentir mais seguro.",
    evitar: {
      frase: "Não tem nada disso, para de ser bobo.",
      motivo: "Negar o medo da criança pequena não faz ele sumir, só ensina que ela não deve mostrar o que sente.",
    },
  },
  {
    key: "esta_com_medo__5_7",
    situacao: "esta_com_medo",
    faixa_etaria: "5_7",
    validacao: "Eu entendo que isso te deixou com medo.",
    limite: "Tô aqui e a gente passa por isso junto.",
    escolha: "Quer conversar sobre o que te assustou ou prefere só ficar pertinho de mim agora?",
    se_persistir: "Tudo bem, vamos com calma, no seu tempo.",
    evitar: {
      frase: "Isso é coisa de bebê ter medo disso.",
      motivo: "Comparar o medo com 'coisa de bebê' envergonha a criança, em vez de ajudar ela a lidar com o que sente.",
    },
  },
  {
    key: "esta_com_medo__8_10",
    situacao: "esta_com_medo",
    faixa_etaria: "8_10",
    validacao: "Percebo que isso te assustou de verdade.",
    limite: "Vamos conversar sobre isso com calma.",
    escolha: "Quer me contar o que aconteceu ou prefere um tempo antes de falar sobre isso?",
    se_persistir: "Tô aqui, sem pressa nenhuma.",
    evitar: {
      frase: "Você já tá grande, não devia ter medo disso.",
      motivo: "Medir o medo pela idade ignora que cada criança lida com as coisas do seu jeito, e faz parecer vergonha sentir medo.",
    },
  },
  {
    key: "esta_com_medo__11_13",
    situacao: "esta_com_medo",
    faixa_etaria: "11_13",
    validacao: "Entendo que essa situação te deixou inseguro.",
    limite: "Vamos conversar sobre isso e pensar juntos no que pode ajudar.",
    escolha: "Quer falar sobre isso agora ou prefere organizar os pensamentos primeiro?",
    se_persistir: "Tudo bem, tô aqui quando você quiser conversar.",
    evitar: {
      frase: "Isso não é motivo pra tanto medo, você tá exagerando.",
      motivo: "Achar que o medo é exagero pode fazer o pré-adolescente parar de contar o que sente no futuro.",
    },
  },
  {
    key: "esta_com_medo__14_17",
    situacao: "esta_com_medo",
    faixa_etaria: "14_17",
    validacao: "Entendo que essa situação te deixou inseguro.",
    limite: "Tô aqui pra conversar sobre isso sempre que precisar.",
    escolha: "Quer conversar agora sobre o que tá sentindo ou prefere pensar um pouco antes?",
    se_persistir: "Sem pressa, continuo aqui quando você quiser falar.",
    evitar: {
      frase: "Você já é quase adulto, tem que superar isso sozinho.",
      motivo: "Cobrar que resolva sozinho isola o adolescente bem no momento em que ele mais precisa de apoio.",
    },
  },

  // ─── esta_chorando ──────────────────────────────────────────────────────────
  {
    key: "esta_chorando__2_4",
    situacao: "esta_chorando",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você tá bem triste.",
    limite: "Pode chorar, eu tô aqui.",
    escolha: "Quer colo ou prefere só ficar pertinho de mim?",
    se_persistir: "Vou ficar aqui até você se acalmar, sem pressa nenhuma.",
    evitar: {
      frase: "Para de chorar já, não é nada demais.",
      motivo: "Dizer que 'não é nada' faz a criança achar que o que ela sente não vale, e ela ainda não sabe relativizar sozinha.",
    },
  },
  {
    key: "esta_chorando__5_7",
    situacao: "esta_chorando",
    faixa_etaria: "5_7",
    validacao: "Percebo que você tá bem triste com isso.",
    limite: "Pode chorar, eu vou ficar aqui com você.",
    escolha: "Quer me contar o que houve agora ou prefere só chorar um pouco primeiro?",
    se_persistir: "Sem pressa, tô bem aqui do seu lado.",
    evitar: {
      frase: "Já chega de choro, você tá fazendo drama.",
      motivo: "Chamar de drama ensina a criança a esconder a tristeza, em vez de mostrar o que sente de um jeito saudável.",
    },
  },
  {
    key: "esta_chorando__8_10",
    situacao: "esta_chorando",
    faixa_etaria: "8_10",
    validacao: "Entendo que isso te machucou de verdade.",
    limite: "Pode chorar à vontade, eu vou ficar por perto.",
    escolha: "Quer conversar sobre o que houve ou prefere um tempo sozinho primeiro?",
    se_persistir: "Tudo bem, venho te ver daqui a pouquinho.",
    evitar: {
      frase: "Já é grande, não chora por isso.",
      motivo: "Ligar o choro à idade ensina a segurar a emoção, e isso tende a voltar de outro jeito mais difícil depois.",
    },
  },
  {
    key: "esta_chorando__11_13",
    situacao: "esta_chorando",
    faixa_etaria: "11_13",
    validacao: "Percebo que isso te afetou bastante.",
    limite: "Pode sentir isso à vontade, tô aqui.",
    escolha: "Quer conversar agora ou prefere um tempo sozinho primeiro?",
    se_persistir: "Sem problema, fico por perto pra quando você quiser conversar.",
    evitar: {
      frase: "Para de ser tão sensível, isso não é motivo pra chorar.",
      motivo: "Chamar de sensível demais ensina o pré-adolescente a desconfiar do que ele mesmo sente.",
    },
  },
  {
    key: "esta_chorando__14_17",
    situacao: "esta_chorando",
    faixa_etaria: "14_17",
    validacao: "Entendo que isso pesou bastante em você.",
    limite: "Pode sentir isso à vontade, não precisa esconder de mim.",
    escolha: "Quer conversar sobre o que tá sentindo ou prefere um tempo sozinho antes?",
    se_persistir: "Tudo bem, continuo por aqui quando você quiser.",
    evitar: {
      frase: "Não sei por que você tá chorando por uma bobagem dessas.",
      motivo: "Chamar de bobagem desmerece o que o adolescente sentiu, e fecha a porta pra ele dividir sentimentos depois.",
    },
  },

  // ─── nao_aceita_desligar_celular ────────────────────────────────────────────
  {
    key: "nao_aceita_desligar_celular__2_4",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria continuar vendo.",
    limite: "Mas agora é hora de desligar.",
    escolha: "Quer desligar sozinho ou prefere que eu conte até três com você?",
    se_persistir: "Vou desligar com calma, e a gente já vai fazer outra coisa junto.",
    evitar: {
      frase: "Se não desligar agora, nunca mais vê tela nenhuma.",
      motivo: "Ameaça grande demais pra cumprir ensina a criança a não levar o limite a sério.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__5_7",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "5_7",
    validacao: "Entendo que você queria terminar o que tava vendo.",
    limite: "Mas o tempo de tela combinado já acabou.",
    escolha: "Quer desligar agora ou terminar esse vídeo em 2 minutinhos?",
    se_persistir: "Vou te ajudar a desligar, e já vamos pra próxima coisa.",
    evitar: {
      frase: "Você vive grudado nessa tela, isso é vício.",
      motivo: "Falar em vício numa criança pequena é exagero e não ajuda a construir um hábito saudável com tela.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__8_10",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "8_10",
    validacao: "Entendo que é difícil parar no meio de um jogo.",
    limite: "Mesmo assim, o tempo combinado acabou.",
    escolha: "Prefere pausar agora e continuar depois, ou terminar essa parte em 5 minutos?",
    se_persistir: "Vou ficar aqui até você desligar, sem pressa.",
    evitar: {
      frase: "Só sabe ficar grudado na tela, não presta pra mais nada.",
      motivo: "Generalizar assim envergonha, em vez de ajudar a construir um limite claro pro uso de tela.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__11_13",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "11_13",
    validacao: "Entendo que no meio de uma partida é mais difícil parar.",
    limite: "Mesmo assim, o horário combinado pra desligar é esse.",
    escolha: "Prefere desligar agora ou terminar a rodada em poucos minutos?",
    se_persistir: "A gente revê esse combinado juntos se ele não tiver funcionando bem.",
    evitar: {
      frase: "Vou tirar seu celular de vez se você não desligar.",
      motivo: "Ameaça grande demais pra cumprir ensina a testar o limite, não a respeitar.",
    },
  },
  {
    key: "nao_aceita_desligar_celular__14_17",
    situacao: "nao_aceita_desligar_celular",
    faixa_etaria: "14_17",
    validacao: "Entendo que parar no meio incomoda.",
    limite: "Ainda assim, o horário combinado pra desligar continua valendo.",
    escolha: "Prefere desligar agora ou terminar em alguns minutos com um alarme marcado?",
    se_persistir: "A gente revê esse combinado com calma outro dia se ele não fizer mais sentido.",
    evitar: {
      frase: "Vocês dessa geração são todos viciados em celular.",
      motivo: "Falar mal de 'geração inteira' soa como julgamento amplo e afasta o adolescente da conversa sobre esse momento específico.",
    },
  },

  // ─── falou_desrespeitoso ────────────────────────────────────────────────────
  {
    key: "falou_desrespeitoso__2_4",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você tá bravo.",
    limite: "Mas não posso deixar você falar assim comigo.",
    escolha: "Quer tentar falar de outro jeito ou prefere um tempo pra se acalmar primeiro?",
    se_persistir: "Vou esperar você se acalmar pra continuarmos a conversa.",
    evitar: {
      frase: "Não fala assim comigo, sua peste!",
      motivo: "Responder com um apelido ruim acaba ensinando exatamente o comportamento que a gente quer corrigir.",
    },
  },
  {
    key: "falou_desrespeitoso__5_7",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "5_7",
    validacao: "Entendo que você tá bravo com a situação.",
    limite: "Mesmo assim, não vou aceitar ser tratada assim.",
    escolha: "Quer tentar de novo com outras palavras ou prefere um tempinho antes?",
    se_persistir: "Vou esperar você se acalmar pra conversarmos com respeito.",
    evitar: {
      frase: "Cadê a educação que eu te dei?",
      motivo: "Essa frase transforma um momento pontual num julgamento sobre a criação, o que gera culpa sem ensinar outro jeito.",
    },
  },
  {
    key: "falou_desrespeitoso__8_10",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "8_10",
    validacao: "Percebo que você tá bravo com alguma coisa.",
    limite: "Mesmo assim, esse tom não é aceitável aqui.",
    escolha: "Quer tentar me dizer de outro jeito o que tá sentindo?",
    se_persistir: "Vou esperar você se acalmar antes de continuarmos.",
    evitar: {
      frase: "Você tá mal-educado que nem fulano.",
      motivo: "Comparar assim cola um rótulo herdado, em vez de tratar como algo pontual e que dá pra corrigir.",
    },
  },
  {
    key: "falou_desrespeitoso__11_13",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "11_13",
    validacao: "Entendo que alguma coisa te deixou irritado.",
    limite: "Mesmo assim, não vou continuar a conversa nesse tom.",
    escolha: "Quer tentar de novo com outro tom ou prefere pausar e retomar depois?",
    se_persistir: "Vou dar um tempo e a gente retoma quando você tiver mais calmo.",
    evitar: {
      frase: "Você tá insuportável, não sei mais o que fazer com você.",
      motivo: "Dizer que não sabe o que fazer joga a responsabilidade pra criança, que não tem ferramenta pra resolver isso sozinha.",
    },
  },
  {
    key: "falou_desrespeitoso__14_17",
    situacao: "falou_desrespeitoso",
    faixa_etaria: "14_17",
    validacao: "Entendo que você tá incomodado com algo.",
    limite: "Ainda assim, preciso que a conversa continue com respeito.",
    escolha: "Prefere retomar com outro tom agora ou pausar e conversar mais tarde?",
    se_persistir: "Vou pausar essa conversa e a gente retoma quando os dois estiverem mais calmos.",
    evitar: {
      frase: "Enquanto morar na minha casa, vai me respeitar.",
      motivo: "Usar autoridade baseada em morar na casa soa como ameaça de poder, e tende a afastar mais do que gerar respeito de verdade.",
    },
  },

  // ─── nao_quer_comer ─────────────────────────────────────────────────────────
  {
    key: "nao_quer_comer__2_4",
    situacao: "nao_quer_comer",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você não tá com fome de comida agora.",
    limite: "Mas essa é a hora da refeição.",
    escolha: "Quer comer sentado na sua cadeirinha ou no colo?",
    se_persistir: "Vou deixar o prato aqui um tempinho, sem forçar.",
    evitar: {
      frase: "Se você não comer, não ganha mais nada de doce nunca.",
      motivo: "Ameaça exagerada sobre comida cria uma relação de medo com a hora de comer, em vez de ajudar a criança a perceber a fome dela.",
    },
  },
  {
    key: "nao_quer_comer__5_7",
    situacao: "nao_quer_comer",
    faixa_etaria: "5_7",
    validacao: "Entendo que hoje você não tá com muita vontade de comer isso.",
    limite: "Mesmo assim, é isso que tem pra essa refeição.",
    escolha: "Quer experimentar um pedacinho primeiro ou prefere comer só o que já conhece hoje?",
    se_persistir: "Tudo bem, vamos deixar por um tempinho e você tenta de novo depois.",
    evitar: {
      frase: "Come tudo ou fica de castigo sem sobremesa.",
      motivo: "Usar comida como prêmio ou castigo ensina a criança a comer por pressão, não por perceber a própria fome.",
    },
  },
  {
    key: "nao_quer_comer__8_10",
    situacao: "nao_quer_comer",
    faixa_etaria: "8_10",
    validacao: "Entendo que hoje o prato não te agradou muito.",
    limite: "Mesmo assim, essa é a comida de hoje.",
    escolha: "Quer comer um pouco de cada coisa ou prefere começar pelo que mais gosta?",
    se_persistir: "Vou deixar o prato aqui, sem pressão, você decide o quanto come.",
    evitar: {
      frase: "Criança que não come isso é sem-vergonha.",
      motivo: "Rotular a criança por causa da comida gera vergonha à toa, sem ajudar de verdade na relação dela com a alimentação.",
    },
  },
  {
    key: "nao_quer_comer__11_13",
    situacao: "nao_quer_comer",
    faixa_etaria: "11_13",
    validacao: "Entendo que você não tá com vontade de comer isso hoje.",
    limite: "Mesmo assim, essa é a opção da refeição de agora.",
    escolha: "Quer se servir de uma quantidade menor pra começar ou prefere comer mais na próxima?",
    se_persistir: "Tudo bem, a gente conversa depois sobre o que você gostaria de ter mais nas refeições.",
    evitar: {
      frase: "Você só come porcaria, não sei o que fazer com você.",
      motivo: "Criticar as escolhas alimentares desse jeito gera vergonha e afasta, em vez de abrir espaço pra conversar sobre alimentação.",
    },
  },
  {
    key: "nao_quer_comer__14_17",
    situacao: "nao_quer_comer",
    faixa_etaria: "14_17",
    validacao: "Entendo que você tem suas preferências sobre o que comer.",
    limite: "Ainda assim, essa é a refeição disponível agora.",
    escolha: "Quer ajustar sua porção ou complementar com algo simples que já tem em casa?",
    se_persistir: "Vamos conversar com calma sobre incluir mais opções que você gosta nas próximas compras.",
    evitar: {
      frase: "Se não comer, fica sem jantar e pronto.",
      motivo: "Punição rígida em torno de comida pode pesar numa relação com a alimentação numa fase sensível pra isso.",
    },
  },

  // ─── nao_quer_tomar_banho ───────────────────────────────────────────────────
  {
    key: "nao_quer_tomar_banho__2_4",
    situacao: "nao_quer_tomar_banho",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria continuar brincando em vez de tomar banho.",
    limite: "Mas agora é hora do banho.",
    escolha: "Quer levar o patinho de borracha ou prefere cantar uma música no banho?",
    se_persistir: "Vou te ajudar a entrar, com calma, sem pressa.",
    evitar: {
      frase: "Se não for tomar banho, ninguém vai gostar de você fedendo.",
      motivo: "Ameaçar com rejeição, mesmo pequena, mexe com o medo da criança de não ser aceita.",
    },
  },
  {
    key: "nao_quer_tomar_banho__5_7",
    situacao: "nao_quer_tomar_banho",
    faixa_etaria: "5_7",
    validacao: "Entendo que você queria continuar brincando um pouco mais.",
    limite: "Mas agora é hora do banho.",
    escolha: "Quer escolher o sabonete de hoje ou a toalha?",
    se_persistir: "Vou te ajudar a começar, e depois você termina sozinho.",
    evitar: {
      frase: "Você tá um nojo, precisa tomar banho urgente.",
      motivo: "Falar assim do corpo da criança soa humilhante, em vez de só marcar que chegou a hora do banho.",
    },
  },
  {
    key: "nao_quer_tomar_banho__8_10",
    situacao: "nao_quer_tomar_banho",
    faixa_etaria: "8_10",
    validacao: "Entendo que dá preguiça de parar o que tá fazendo pra tomar banho.",
    limite: "Mesmo assim, esse é o horário combinado.",
    escolha: "Prefere tomar banho agora ou em 10 minutos, com alarme marcado?",
    se_persistir: "Vou lembrar você de novo em alguns minutos, sem gritar.",
    evitar: {
      frase: "Você é sujo, ninguém vai querer chegar perto de você.",
      motivo: "Julgamento assim sobre higiene machuca a autoestima em vez de ajudar a construir o hábito.",
    },
  },
  {
    key: "nao_quer_tomar_banho__11_13",
    situacao: "nao_quer_tomar_banho",
    faixa_etaria: "11_13",
    validacao: "Entendo que às vezes dá preguiça de parar o que tá fazendo.",
    limite: "Mesmo assim, o banho continua fazendo parte da rotina.",
    escolha: "Prefere tomar banho agora ou definir um horário fixo que funcione melhor pra você?",
    se_persistir: "Vamos combinar um horário que você lembre sozinho, sem eu precisar avisar toda vez.",
    evitar: {
      frase: "Você tá fedendo, ninguém vai querer sentar perto de você.",
      motivo: "Comentário sobre o cheiro/corpo do adolescente é humilhante numa fase de muita sensibilidade com a própria imagem.",
    },
  },
  {
    key: "nao_quer_tomar_banho__14_17",
    situacao: "nao_quer_tomar_banho",
    faixa_etaria: "14_17",
    validacao: "Entendo que você tem seu próprio ritmo pra essas coisas.",
    limite: "Ainda assim, higiene é algo que a gente não abre mão em casa.",
    escolha: "Prefere ajustar o horário do banho pra outro momento do dia que funcione melhor?",
    se_persistir: "Vamos conversar sobre um horário que realmente funcione pra sua rotina.",
    evitar: {
      frase: "Isso é falta de higiene, que nojo de você.",
      motivo: "Expressar nojo da própria pessoa, não só do comportamento, machuca profundamente a autoestima do adolescente.",
    },
  },

  // ─── nao_quer_fazer_licao_de_casa ───────────────────────────────────────────
  {
    key: "nao_quer_fazer_licao_de_casa__2_4",
    situacao: "nao_quer_fazer_licao_de_casa",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você queria continuar brincando.",
    limite: "Mas agora é a hora da atividade.",
    escolha: "Quer fazer sentado na mesinha ou no chão comigo perto?",
    se_persistir: "Vou ficar aqui te ajudando a começar.",
    evitar: {
      frase: "Se não fizer, não vai saber nada quando crescer.",
      motivo: "Ameaça sobre o futuro distante não faz sentido pra uma criança pequena e só gera ansiedade à toa.",
    },
  },
  {
    key: "nao_quer_fazer_licao_de_casa__5_7",
    situacao: "nao_quer_fazer_licao_de_casa",
    faixa_etaria: "5_7",
    validacao: "Entendo que você queria brincar em vez de fazer a lição.",
    limite: "Mas a lição é parte do que precisa ser feito hoje.",
    escolha: "Quer fazer a lição antes ou depois de um lanchinho rápido?",
    se_persistir: "Vou sentar do seu lado pra te ajudar a começar.",
    evitar: {
      frase: "Se não fizer a lição, você vai ficar pra trás dos outros.",
      motivo: "Comparar com os colegas gera ansiedade em vez de ajudar a criança a lidar com a dificuldade da tarefa.",
    },
  },
  {
    key: "nao_quer_fazer_licao_de_casa__8_10",
    situacao: "nao_quer_fazer_licao_de_casa",
    faixa_etaria: "8_10",
    validacao: "Entendo que dá preguiça de começar a lição.",
    limite: "Mesmo assim, ela precisa ser feita hoje.",
    escolha: "Prefere fazer a parte mais fácil primeiro ou a mais difícil?",
    se_persistir: "Vou ficar por perto se você precisar de ajuda com alguma parte.",
    evitar: {
      frase: "Você é preguiçoso, por isso não vai bem na escola.",
      motivo: "Rotular como preguiçoso ignora possíveis dificuldades reais com a matéria e machuca a autoestima.",
    },
  },
  {
    key: "nao_quer_fazer_licao_de_casa__11_13",
    situacao: "nao_quer_fazer_licao_de_casa",
    faixa_etaria: "11_13",
    validacao: "Entendo que você não tá com vontade nenhuma de fazer isso agora.",
    limite: "Mesmo assim, a lição precisa ser entregue.",
    escolha: "Prefere fazer agora em um bloco ou dividir em duas partes hoje?",
    se_persistir: "Vamos combinar um horário curto pra isso ficar resolvido ainda hoje.",
    evitar: {
      frase: "Se você não estudar, vai ser um fracasso na vida.",
      motivo: "Ligar uma lição específica ao 'fracasso na vida' é exagero e só gera ansiedade, sem ajudar com a tarefa em si.",
    },
  },
  {
    key: "nao_quer_fazer_licao_de_casa__14_17",
    situacao: "nao_quer_fazer_licao_de_casa",
    faixa_etaria: "14_17",
    validacao: "Entendo que hoje você não tá com vontade de estudar.",
    limite: "Ainda assim, isso precisa ser resolvido até o prazo.",
    escolha: "Prefere organizar um horário específico pra isso hoje ou dividir em partes menores essa semana?",
    se_persistir: "Vamos conversar sobre como organizar melhor esses prazos daqui pra frente.",
    evitar: {
      frase: "Se você não passar de ano, pode esquecer seus planos.",
      motivo: "Ameaça grande sobre o futuro aumenta a pressão sem ajudar de fato a resolver a tarefa de agora.",
    },
  },

  // ─── nao_quer_dividir_brinquedo ─────────────────────────────────────────────
  {
    key: "nao_quer_dividir_brinquedo__2_4",
    situacao: "nao_quer_dividir_brinquedo",
    faixa_etaria: "2_4",
    validacao: "Eu sei que você tá gostando muito desse brinquedo.",
    limite: "Mas aqui a gente também compartilha com os amigos.",
    escolha: "Quer emprestar esse brinquedo ou prefere oferecer outro no lugar?",
    se_persistir: "Vou te ajudar a encontrar um jeito dos dois brincarem.",
    evitar: {
      frase: "Se não emprestar, ninguém vai querer brincar com você nunca mais.",
      motivo: "Ameaça de rejeição é grande demais pra uma criança pequena e só gera medo, não generosidade de verdade.",
    },
  },
  {
    key: "nao_quer_dividir_brinquedo__5_7",
    situacao: "nao_quer_dividir_brinquedo",
    faixa_etaria: "5_7",
    validacao: "Entendo que você não quer parar de brincar com esse brinquedo agora.",
    limite: "Mesmo assim, a gente pode combinar um jeito de dividir.",
    escolha: "Quer emprestar por alguns minutos com um cronômetro ou prefere trocar por outro brinquedo?",
    se_persistir: "Vou ficar por perto ajudando vocês a combinar.",
    evitar: {
      frase: "Você é egoísta por não querer dividir.",
      motivo: "Chamar de egoísta numa fase em que a criança ainda tá aprendendo a compartilhar cola um rótulo injusto.",
    },
  },
  {
    key: "nao_quer_dividir_brinquedo__8_10",
    situacao: "nao_quer_dividir_brinquedo",
    faixa_etaria: "8_10",
    validacao: "Entendo que você não quer parar de usar isso agora.",
    limite: "Mesmo assim, dividir faz parte de brincar junto.",
    escolha: "Quer combinar um tempo pra cada um ou prefere brincar juntos com o mesmo brinquedo?",
    se_persistir: "Vou ficar por perto pra ajudar vocês a combinarem.",
    evitar: {
      frase: "Só sabe pensar em você mesmo.",
      motivo: "Julgamento sobre o caráter da criança, por causa de um momento pontual, machuca mais do que ensina.",
    },
  },
  {
    key: "nao_quer_dividir_brinquedo__11_13",
    situacao: "nao_quer_dividir_brinquedo",
    faixa_etaria: "11_13",
    validacao: "Entendo que você não quer emprestar isso agora.",
    limite: "Mesmo assim, vamos pensar num jeito de todo mundo ficar bem com isso.",
    escolha: "Quer combinar um horário pra usar ou prefere resolver de outro jeito?",
    se_persistir: "Vamos conversar sobre isso com calma se não conseguirem combinar sozinhos.",
    evitar: {
      frase: "Você é muito mão-fechada com as coisas.",
      motivo: "Rotular como 'mão-fechada' julga o caráter em vez de ajudar a resolver a situação específica.",
    },
  },
  {
    key: "nao_quer_dividir_brinquedo__14_17",
    situacao: "nao_quer_dividir_brinquedo",
    faixa_etaria: "14_17",
    validacao: "Entendo que você não quer emprestar isso agora.",
    limite: "Mesmo assim, vamos pensar num jeito que funcione pra todo mundo em casa.",
    escolha: "Quer combinar regras claras sobre isso ou prefere resolver direto com a pessoa envolvida?",
    se_persistir: "Vamos conversar com calma sobre isso quando fizer sentido pra você.",
    evitar: {
      frase: "Você é muito egoísta, só pensa em você.",
      motivo: "Julgamento sobre o caráter, num momento pontual, afasta mais do que ajuda a resolver a situação real.",
    },
  },

  // ─── fez_birra_em_lugar_publico ─────────────────────────────────────────────
  {
    key: "fez_birra_em_lugar_publico__2_4",
    situacao: "fez_birra_em_lugar_publico",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você tá bem bravo agora, mesmo aqui fora.",
    limite: "Mas não posso deixar você se machucar ou machucar alguém aqui.",
    escolha: "Quer sair um pouquinho comigo pra um lugar mais calmo ou prefere ficar aqui respirando fundo?",
    se_persistir: "Vou ficar bem pertinho até você se acalmar, sem pressa.",
    evitar: {
      frase: "Para com isso, tá todo mundo olhando pra gente.",
      motivo: "Focar no que os outros vão pensar, em vez do que a criança sente, ensina que a opinião alheia importa mais do que ela mesma.",
    },
  },
  {
    key: "fez_birra_em_lugar_publico__5_7",
    situacao: "fez_birra_em_lugar_publico",
    faixa_etaria: "5_7",
    validacao: "Eu vejo que você ficou muito bravo aqui fora.",
    limite: "Mesmo assim, a gente não pode ficar gritando desse jeito no meio das pessoas.",
    escolha: "Quer respirar fundo comigo ou prefere ir pra um cantinho mais calmo?",
    se_persistir: "Vou ficar aqui com você até passar, sem me importar com quem tá olhando.",
    evitar: {
      frase: "Que vergonha de você fazendo esse escândalo aqui.",
      motivo: "Falar em vergonha faz a criança associar a própria emoção a algo ruim, em vez de aprender a lidar com ela.",
    },
  },
  {
    key: "fez_birra_em_lugar_publico__8_10",
    situacao: "fez_birra_em_lugar_publico",
    faixa_etaria: "8_10",
    validacao: "Percebo que você ficou bem bravo com a situação.",
    limite: "Mesmo assim, a gente precisa se acalmar antes de continuar aqui.",
    escolha: "Quer um tempinho pra respirar ou prefere conversar sobre o que aconteceu agora?",
    se_persistir: "Vamos pra um lugar mais tranquilo até você se acalmar.",
    evitar: {
      frase: "Você tá me deixando com vergonha na frente de todo mundo.",
      motivo: "Colocar a vergonha do adulto como peso na criança ensina ela a esconder a emoção em vez de aprender a lidar com ela.",
    },
  },
  {
    key: "fez_birra_em_lugar_publico__11_13",
    situacao: "fez_birra_em_lugar_publico",
    faixa_etaria: "11_13",
    validacao: "Entendo que isso te deixou muito irritado, mesmo aqui fora.",
    limite: "Mesmo assim, precisamos abaixar o tom pra continuar essa conversa aqui.",
    escolha: "Quer continuar em outro tom ou prefere a gente sair e conversar em outro lugar?",
    se_persistir: "Vamos dar um tempo e continuar essa conversa mais tarde, com calma.",
    evitar: {
      frase: "Você só sabe me envergonhar na frente das pessoas.",
      motivo: "Colocar o foco na vergonha do adulto, em vez do que o pré-adolescente sente, afasta e não ajuda a resolver.",
    },
  },
  {
    key: "fez_birra_em_lugar_publico__14_17",
    situacao: "fez_birra_em_lugar_publico",
    faixa_etaria: "14_17",
    validacao: "Percebo que isso te deixou bem incomodado, mesmo aqui fora.",
    limite: "Mesmo assim, precisamos continuar essa conversa num tom mais calmo.",
    escolha: "Prefere continuar aqui com calma ou conversar em outro momento, com mais privacidade?",
    se_persistir: "Tudo bem, a gente retoma essa conversa quando fizer mais sentido.",
    evitar: {
      frase: "Você tá me humilhando na frente de todo mundo.",
      motivo: "Colocar a própria humilhação como argumento central desvia da situação real e faz o adolescente se sentir culpado pelo sentimento do adulto.",
    },
  },

  // ─── disse_que_odeia_voce ───────────────────────────────────────────────────
  {
    key: "disse_que_odeia_voce__2_4",
    situacao: "disse_que_odeia_voce",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você tá bem bravo comigo agora.",
    limite: "Mesmo bravo, eu continuo aqui e te amo do mesmo jeito.",
    escolha: "Quer um abraço ou prefere ficar um pouquinho sozinho até se acalmar?",
    se_persistir: "Vou ficar por perto esperando você se acalmar.",
    evitar: {
      frase: "Que absurdo falar isso com sua mãe, cadê o respeito?",
      motivo: "Reagir com choque ou cobrança de respeito ensina a criança pequena a esconder a raiva em vez de aprender a nomear o que sente.",
    },
  },
  {
    key: "disse_que_odeia_voce__5_7",
    situacao: "disse_que_odeia_voce",
    faixa_etaria: "5_7",
    validacao: "Eu entendo que você tá bem bravo comigo agora.",
    limite: "Mesmo assim, eu continuo aqui e a gente vai resolver isso juntos.",
    escolha: "Quer me contar o que te deixou tão bravo ou prefere um tempinho primeiro?",
    se_persistir: "Tudo bem, eu espero você se acalmar pra conversar.",
    evitar: {
      frase: "Depois de tudo que eu faço por você, fala isso comigo?",
      motivo: "Cobrar gratidão nesse momento coloca um peso emocional grande demais pra criança processar, e desvia do sentimento real dela.",
    },
  },
  {
    key: "disse_que_odeia_voce__8_10",
    situacao: "disse_que_odeia_voce",
    faixa_etaria: "8_10",
    validacao: "Percebo que você tá bem bravo comigo agora.",
    limite: "Mesmo assim, eu continuo aqui pra conversar sobre isso.",
    escolha: "Quer me contar o que aconteceu ou prefere se acalmar primeiro?",
    se_persistir: "Tô aqui quando você quiser conversar com mais calma.",
    evitar: {
      frase: "Você não sabe o que tá falando, isso magoa demais.",
      motivo: "Focar na própria mágoa em vez de entender a raiva da criança faz ela se sentir culpada em vez de compreendida.",
    },
  },
  {
    key: "disse_que_odeia_voce__11_13",
    situacao: "disse_que_odeia_voce",
    faixa_etaria: "11_13",
    validacao: "Entendo que você tá bem bravo comigo agora.",
    limite: "Mesmo assim, quero entender o que te deixou tão irritado.",
    escolha: "Quer conversar sobre isso agora ou prefere um tempo antes?",
    se_persistir: "Tudo bem, tô aqui quando você quiser retomar essa conversa.",
    evitar: {
      frase: "Depois dessa eu não vou mais fazer nada por você.",
      motivo: "Ameaçar retirar o afeto ou apoio como resposta a um momento de raiva ensina que o carinho depende do comportamento.",
    },
  },
  {
    key: "disse_que_odeia_voce__14_17",
    situacao: "disse_que_odeia_voce",
    faixa_etaria: "14_17",
    validacao: "Entendo que você tá bem irritado comigo agora.",
    limite: "Mesmo assim, continuo aqui e quero entender o que houve.",
    escolha: "Quer conversar sobre isso agora ou prefere um tempo antes de retomarmos?",
    se_persistir: "Tudo bem, sigo disponível quando você quiser conversar.",
    evitar: {
      frase: "Depois de tudo que eu fiz, você me trata assim?",
      motivo: "Cobrar gratidão nesse momento transforma a conversa numa disputa de quem sofreu mais, em vez de resolver o que gerou a raiva.",
    },
  },

  // ─── teve_ciume_do_irmao ────────────────────────────────────────────────────
  {
    key: "teve_ciume_do_irmao__2_4",
    situacao: "teve_ciume_do_irmao",
    faixa_etaria: "2_4",
    validacao: "Eu vejo que você quer minha atenção agora também.",
    limite: "Eu tô aqui pros dois, e agora é a vez do seu irmão.",
    escolha: "Quer ficar pertinho enquanto eu cuido dele ou prefere brincar de algo enquanto espera sua vez?",
    se_persistir: "Assim que eu terminar, vou dar atenção só pra você também.",
    evitar: {
      frase: "Para de implicar com seu irmão, ele é bebê.",
      motivo: "Minimizar o ciúme como implicância ignora que é um sentimento real da criança maior, que também precisa de atenção.",
    },
  },
  {
    key: "teve_ciume_do_irmao__5_7",
    situacao: "teve_ciume_do_irmao",
    faixa_etaria: "5_7",
    validacao: "Entendo que às vezes parece que ele recebe mais atenção.",
    limite: "Mesmo assim, cada um de vocês tem seu momento comigo.",
    escolha: "Quer escolher uma coisa pra fazermos só nós dois mais tarde?",
    se_persistir: "Vou separar um tempinho só nosso ainda hoje.",
    evitar: {
      frase: "Você já é grande, não precisa mais de tanta atenção.",
      motivo: "Dizer que já é grande demais pra precisar de atenção nega uma necessidade real, que não desaparece só por causa da idade.",
    },
  },
  {
    key: "teve_ciume_do_irmao__8_10",
    situacao: "teve_ciume_do_irmao",
    faixa_etaria: "8_10",
    validacao: "Percebo que você sente que ele fica com mais atenção às vezes.",
    limite: "Mesmo assim, eu me importo com os dois do mesmo jeito.",
    escolha: "Quer conversar sobre isso agora ou prefere que a gente reserve um tempo só nosso essa semana?",
    se_persistir: "Vamos combinar um momento só nosso pra essa semana.",
    evitar: {
      frase: "Você tá com ciúme bobo do seu irmão.",
      motivo: "Chamar o ciúme de bobo faz a criança se sentir errada por sentir algo real, em vez de ajudá-la a lidar com isso.",
    },
  },
  {
    key: "teve_ciume_do_irmao__11_13",
    situacao: "teve_ciume_do_irmao",
    faixa_etaria: "11_13",
    validacao: "Entendo que às vezes parece que a atenção não tá equilibrada entre vocês.",
    limite: "Mesmo assim, eu me importo com os dois, cada um do seu jeito.",
    escolha: "Quer conversar sobre isso com calma ou prefere que a gente combine mais momentos só nossos?",
    se_persistir: "Vamos organizar um tempo específico só nosso essa semana.",
    evitar: {
      frase: "Você devia ter vergonha de ter ciúme do próprio irmão.",
      motivo: "Envergonhar por sentir ciúme faz o pré-adolescente esconder o sentimento em vez de aprender a lidar com ele.",
    },
  },
  {
    key: "teve_ciume_do_irmao__14_17",
    situacao: "teve_ciume_do_irmao",
    faixa_etaria: "14_17",
    validacao: "Entendo que às vezes parece que a atenção pesa mais pra um lado.",
    limite: "Mesmo assim, o que sinto por vocês dois não é uma disputa.",
    escolha: "Quer conversar sobre isso com calma ou prefere que a gente ajuste algo na nossa rotina?",
    se_persistir: "Vamos conversar com calma sobre isso quando fizer sentido pra você.",
    evitar: {
      frase: "Já devia ter passado dessa fase de ciúme.",
      motivo: "Achar que ciúme é 'fase que devia ter passado' ignora que sentimentos assim podem voltar em diferentes momentos, mesmo mais velho.",
    },
  },

  // ─── demora_para_se_vestir ──────────────────────────────────────────────────
  {
    key: "demora_para_se_vestir__2_4",
    situacao: "demora_para_se_vestir",
    faixa_etaria: "2_4",
    validacao: "Eu sei que vestir roupa não é a parte favorita sua agora.",
    limite: "Mas a gente precisa terminar de se vestir pra sair.",
    escolha: "Quer vestir a camiseta ou a calça primeiro?",
    se_persistir: "Vou te ajudar com o que for mais difícil.",
    evitar: {
      frase: "Se não vestir logo, vou te deixar aí de pijama na rua.",
      motivo: "Ameaça de expor a criança envergonhada em público é exagerada e só gera medo, não colaboração.",
    },
  },
  {
    key: "demora_para_se_vestir__5_7",
    situacao: "demora_para_se_vestir",
    faixa_etaria: "5_7",
    validacao: "Entendo que vestir roupa hoje tá difícil.",
    limite: "Mesmo assim, a gente precisa sair em alguns minutos.",
    escolha: "Quer se vestir sozinho ou prefere que eu ajude com os botões?",
    se_persistir: "Vou ficar contando os minutos junto com você pra gente não se atrasar.",
    evitar: {
      frase: "Você é lento demais, sempre atrasa todo mundo.",
      motivo: "Rotular como lento gera vergonha em vez de ajudar a criança a organizar o próprio ritmo.",
    },
  },
  {
    key: "demora_para_se_vestir__8_10",
    situacao: "demora_para_se_vestir",
    faixa_etaria: "8_10",
    validacao: "Entendo que hoje tá difícil de se organizar pra sair.",
    limite: "Mesmo assim, precisamos sair no horário combinado.",
    escolha: "Prefere separar a roupa na noite anterior ou usar um cronômetro de manhã?",
    se_persistir: "Vou te lembrar do tempo que falta, sem ficar repetindo toda hora.",
    evitar: {
      frase: "Você não tem jeito, sempre atrasa todo mundo.",
      motivo: "Dizer que 'não tem jeito' fecha a porta pra melhorar, em vez de ajudar a criar uma rotina que funcione.",
    },
  },
  {
    key: "demora_para_se_vestir__11_13",
    situacao: "demora_para_se_vestir",
    faixa_etaria: "11_13",
    validacao: "Entendo que organizar tudo de manhã pode ser corrido.",
    limite: "Mesmo assim, a gente precisa sair no horário combinado.",
    escolha: "Prefere deixar a roupa separada na noite anterior ou ajustar o horário de acordar?",
    se_persistir: "Vamos ajustar a rotina de manhã juntos se ela não tiver funcionando.",
    evitar: {
      frase: "Você é uma lesma, nunca fica pronto a tempo.",
      motivo: "Apelido depreciativo sobre o ritmo do pré-adolescente machuca sem ajudar a resolver o problema real de organização.",
    },
  },
  {
    key: "demora_para_se_vestir__14_17",
    situacao: "demora_para_se_vestir",
    faixa_etaria: "14_17",
    validacao: "Entendo que sua manhã tem seu próprio ritmo.",
    limite: "Ainda assim, a gente precisa sair no horário combinado.",
    escolha: "Prefere ajustar o horário de acordar ou organizar melhor a noite anterior?",
    se_persistir: "Vamos conversar sobre como ajustar essa rotina de um jeito que funcione melhor pra você.",
    evitar: {
      frase: "Você é um desorganizado, nunca vai conseguir nada na vida assim.",
      motivo: "Ligar um atraso pontual ao 'futuro na vida' é exagero e machuca a autoestima sem ajudar com a rotina de agora.",
    },
  },
];
